[package]
name = "ethnum"
version = "1.0.3"
authors = ["Nicholas Rodrigues Lordello <nlordell@gmail.com>"]
edition = "2018"
description = "256-bit unsigned integer implementation"
documentation = "https://docs.rs/ethnum"
readme = "README.md"
homepage = "https://github.com/nlordell/ethnum-rs"
repository = "https://github.com/nlordell/ethnum-rs"
license = "MIT OR Apache-2.0"
keywords = ["integer", "u256", "ethereum"]
categories = ["cryptography::cryptocurrencies", "mathematics", "no-std"]

[workspace]
members = [
  "bench",
  "intrinsics",
]

[features]
llvm-intrinsics = ["ethnum-intrinsics"]
default = ["serde"]

[dependencies]
ethnum-intrinsics = { version = "1", path = "intrinsics", optional = true }
serde = { version = "1", optional = true }

[dev-dependencies]
serde_derive = "1"
serde_json = "1"
